site_name: BTCRecover
site_url: https://cryptoguide.tips
site_description: Documentation for BTCRecover
site_author: Stephen Rothery

repo_url: https://github.com/3rdIteration/btcrecover
edit_uri: ""

theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django

nav:
    - Home: index.md
    - Installation & Testing:
        - Installing BTCRecover: INSTALL.md
        - GPU Acceleration: GPU_Acceleration.md
    - Using BTCRecover:
        - Seed Recovery Quickstart: Seedrecover_Quick_Start_Guide
        - Password Recovery Quickstart: TUTORIAL.md
        - Tokenlist Files: tokenlist_file.md
        - Passwordlist Files: passwordlist_file.md
        - BIP39 Seed/Token Lists: BIP39_descrambling_seedlists.md
        - Limitations & Caveats: Limitations_and_Caveats.md
        - Recovery without Addresses (Address Database): Creating_and_Using_AddressDB.md
        - Trustless (or Cloud) Recovery - Creating Wallet Extracts: Extract_Scripts.md
    - Usage Examples:
        - Descrambling a 12 word seed: Usage_Examples/2020-05-02_Descrambling_a_12_word_seed/Example.md
        - Recovering Blockchain.com wallet: Usage_Examples/2020-05-08_Recovering_Blockchain_Wallet_Passwords/Example.md
        - Multi-Worker Descrambling: Usage_Examples/2020-05-23_multi_device_descrambling_12_word_seed_with_extras/Example.md
        - Multi-GPU Cloud Based Recovery: Usage_Examples/2020-10-06_Multi-GPU_with_vastai/Multi-GPU_with_vastai.md
    - About:
        - Credits: CREDITS.md
        - License: licence.md

plugins:
    - search
