blank_issues_enabled: false
contact_links:
  - name: CryptoGuide YouTube channel
    url: https://www.youtube.com/channel/UCEviBQwLv-yfv3BErm0ojHg/
    about: BTCRecover Tutorials, free support happens in the comments section. (I reply to everything)
  - name: Paid Support Request
    url: https://cryptoguide.tips/recovery-services-consultations/
    about: Request Paid Private support or Trusted Recoveries.
