blank_issues_enabled: false
contact_links:
  - name: CryptoGuide YouTube chnnel
    url: https://www.youtube.com/channel/UCEviBQwLv-yfv3BErm0ojHg/
    about: BTCRecover Tutorials, free supprot happens in the comments section
  - name: Paid Support Request
    url: https://cryptoguide.tips/recovery-services-consultations/
    about: Request Paid Private support or Trusted Recoveries.
