name: Termux CI Tests

on:
  schedule:
    - cron: "0 0 * * 6"
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  termux:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Enable QEMU
        run: |
          docker run --rm --privileged aptman/qus -s -- -p aarch64
      - name: Run tests inside Termux
        run: |
          docker run --rm --security-opt seccomp:unconfined \
            -v ${{ github.workspace }}:/src \
            --entrypoint /entrypoint_root.sh \
            termux/termux-docker:aarch64 \
            bash -lc "\
              pkg update -y && \
              pkg install -y python git autoconf automake build-essential libtool pkg-config && \
              cd /src && \
              python -m pip install --upgrade pip && \
              pip install -r requirements.txt && \
              python run-all-tests.py -vv\
            "

  termux-full:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Enable QEMU
        run: |
          docker run --rm --privileged aptman/qus -s -- -p aarch64
      - name: Run tests inside Termux (full requirements)
        run: |
          docker run --rm --security-opt seccomp:unconfined \
            -v ${{ github.workspace }}:/src \
            --entrypoint /entrypoint_root.sh \
            termux/termux-docker:aarch64 \
            bash -lc "\
              pkg update -y && \
              pkg install -y python git autoconf automake build-essential libtool pkg-config && \
              cd /src && \
              python -m pip install --upgrade pip && \
              pip install -r requirements-full.txt && \
              python run-all-tests.py -vv\
            "
